package com.viktoriagavrosh.mylibrary.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF803FAF)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF3DAFF)
val md_theme_light_onPrimaryContainer = Color(0xFF2E004D)
val md_theme_light_secondary = Color(0xFF584EBF)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE3DFFF)
val md_theme_light_onSecondaryContainer = Color(0xFF140067)
val md_theme_light_tertiary = Color(0xFF1D5FA6)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD4E3FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001C3A)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1D1B1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1D1B1E)
val md_theme_light_surfaceVariant = Color(0xFFEADFEA)
val md_theme_light_onSurfaceVariant = Color(0xFF4B454D)
val md_theme_light_outline = Color(0xFF7C757E)
val md_theme_light_inverseOnSurface = Color(0xFFF6EFF3)
val md_theme_light_inverseSurface = Color(0xFF322F33)
val md_theme_light_inversePrimary = Color(0xFFE2B6FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF803FAF)
val md_theme_light_outlineVariant = Color(0xFFCDC3CE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFE2B6FF)
val md_theme_dark_onPrimary = Color(0xFF4D007B)
val md_theme_dark_primaryContainer = Color(0xFF662395)
val md_theme_dark_onPrimaryContainer = Color(0xFFF3DAFF)
val md_theme_dark_secondary = Color(0xFFC5C0FF)
val md_theme_dark_onSecondary = Color(0xFF281590)
val md_theme_dark_secondaryContainer = Color(0xFF3F34A6)
val md_theme_dark_onSecondaryContainer = Color(0xFFE3DFFF)
val md_theme_dark_tertiary = Color(0xFFA5C8FF)
val md_theme_dark_onTertiary = Color(0xFF00315E)
val md_theme_dark_tertiaryContainer = Color(0xFF004785)
val md_theme_dark_onTertiaryContainer = Color(0xFFD4E3FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1B1E)
val md_theme_dark_onBackground = Color(0xFFE7E1E5)
val md_theme_dark_surface = Color(0xFF1D1B1E)
val md_theme_dark_onSurface = Color(0xFFE7E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF4B454D)
val md_theme_dark_onSurfaceVariant = Color(0xFFCDC3CE)
val md_theme_dark_outline = Color(0xFF968E98)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE7E1E5)
val md_theme_dark_inversePrimary = Color(0xFF803FAF)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFE2B6FF)
val md_theme_dark_outlineVariant = Color(0xFF4B454D)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFA765D7)
